blank_issues_enabled: false
contact_links:
  - name: View Documentation
    url: https://offalynne.grebedoc.dev/Input/
    about: Find common answers and other information 
  - name: Discuss on Discord
    url: https://discord.com/invite/hwgWpnsNw2
    about: Ask and answer further questions
